### ISSUE TITLE
Meta is never set

### ISSUE THREAD

**Issue by glsignal** [beauby/jsonapi_parser#15]
Hey there, I was digging through the implementation here for why `meta` was showing up as nil, even though the flag `@meta_defined` is set.

https://github.com/beauby/jsonapi_parser/blob/master/lib/json/api/document.rb#L79 checks that `meta_hash` is indeed a hash and fails if it's not valid, but it never returns anything and so meta remains `nil`.

I see there isn't a test case for this yet, so are there plans around how you want to load meta or would it be sufficient to return `meta_hash` in `parse_meta` (leaving it as a regular hash, rather than an object of some sort as in `parse_data`)?

If you're alright with just a hash being there then I can submit a PR pretty promptly, otherwise let's discuss how to implement it.

**Comment by beauby** [comment]
Closing this as #16 was merged.
